project:
  type: website
  render:
    - "*.qmd"
    - "!todo/*"
    - "!archive_2425/*"
  output-dir: ../docs/2526/labs/

website:
  title: "DAPR1"
  page-navigation: true
  reader-mode: true
  back-to-top-navigation: true
  search: true
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Lab Materials"
    right:
      - text: "Readings"
      - text: "About"
        
bibliography: biblio.bib

format:
  html:
    highlight-style: a11y
    theme:
      light: flatly
      dark: darkly
    css: assets/styles.css
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    toc: true
    code-link: true
    sidebar: true
    number-sections: true
