project:
  type: website
  output-dir: docs

website:
  title: "DAPR1"
  body-footer: _footer.html
  navbar:
    left:
      - sidebar:sem1labs
      - sidebar:sem2labs
    right:
      - href: index.qmd
        text: Home
      - sidebar:sem12read
      - about.qmd

  sidebar:
    - id: sem1labs
      title: "Semester 1"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: "S1-W1: Research design & data"
          file: 1_01_design_and_data.qmd
        - text: "S1-W2"
        - text: "S1-W3"
        - text: "S1-W4"
        - text: "S1-W5"
        - text: "S1-W6: Formative Feedb. A"
        - text: "S1-W7"
        - text: "S1-W8"
        - text: "S1-W9"
        - text: "S1-W10"
        - text: "S1-W11"
        - text: "S1-W12: Formative Feedb. B"
  
    - id: sem2labs
      title: "Semester 2"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - 1_01_design_and_data.qmd
        
    - id: sem12read
      title: "Readings"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - 1_01_design_and_data.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    code-link: true
    include-in-header: assets/toggling.html



