project:
  type: website
  render:
    - "*.qmd"
  output-dir: ../docs/2223/labs/

website:
  title: "DAPR1"
  page-footer: 
    left: © Copyright 2019-2022 [The University of Edinburgh](https://www.ed.ac.uk/). Site licensed under the [GNU AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html) license.
  page-navigation: true
  reader-mode: true
  navbar:
    left:
      - sidebar:sem1labs
      - sidebar:sem2labs
    right:
      - sidebar:sem1read
      - sidebar:sem2read
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    - id: sem1labs
      title: "Semester 1"
      style: "floating"
      background: light
      collapse-level: 2
      contents: 
        - text: "S1-W1: Research design & data"
          file: 1_01_design_and_data.qmd
        - text: "S1-W2: Categorical data"
          file: 1_02_categorical_data.qmd
        - text: "S1-W3 Numeric data"
          file: 1_03_numeric_data.qmd
        - text: "S1-W4: Relationships"
          file: 1_04_relationships.qmd
        - text: "S1-W5: Formative Report A"
          file: 1_05_formative_report_a.qmd
        - text: "S1-W6: Formative Feedback A"
        - text: "S1-W7: Probability Theory"
          file: 1_07_prob_theory.qmd
        - text: "S1-W8: Probability Rules"
          file: 1_08_prob_rules.qmd
        - text: "S1-W9: Discrete Random Variables"
          file: 1_09_discrete_dist.qmd
        - text: "S1-W10: Continuous Random Variables"
          file: 1_10_cont_dist.qmd
        - text: "S1-W11: Sampling"
          file: 1_11_sampling.qmd
        # - text: "S1-W12: Formative Feedback B"
  
    - id: sem2labs
      title: "Semester 2"
      style: "floating"
      background: light
      collapse-level: 2
      contents: 
        - text: "S1-W1: Confidence intervals"
          file: 2_01_confint.qmd
        - text: "S2-W2"
        - text: "S2-W3"
        - text: "S2-W4"
        - text: "S2-W5"
        - text: "S2-FLW:"
        - text: "S2-W6"
        - text: "S2-W7"
        - text: "S2-W8"
        - text: "S2-W9"
        - text: "S2-W10"
        - text: "S2-W11:"
        
    - id: sem1read
      title: "Readings - Sem. 1"
      style: "floating"
      background: light
      collapse-level: 2
      contents: 
        - text: "S1-W1: Getting started with R and RStudio"
          file: rd1_01.qmd
        - text: "S1-W2: Categorical data"
          file: rd1_02.qmd
        - text: "S1-W3: Numeric data"
          file: rd1_03.qmd
        - text: "S1-W4: Relationships"
          file: rd1_04.qmd
        - text: "S1-W5: Functions"
          file: rd1_05.qmd
        - text: "S1-W6: Formative feedback week"
        - text: "S1-W7: Probability 1"
          file: rd1_07.qmd
        - text: "S1-W8: Probability 2"
          file: rd1_08.qmd
        - text: "S1-W9: Discrete random variables"
          file: rd1_09.qmd
        - text: "S1-W10: Continuous random variables"
          file: rd1_10.qmd
        - text: "S1-W11: Sampling"
          file: rd1_11.qmd
        - text: "S1-W12: Formative feedback week"
    
    - id: sem2read
      title: "Readings - Sem. 2"
      style: "floating"
      background: light
      collapse-level: 2
      contents: 
        - text: "S2-W1: Confidence intervals"
          file: rd2_01.qmd

bibliography: biblio.bib

format:
  html:
    highlight-style: a11y
    theme:
      light: flatly
      dark: darkly
    css: assets/styles.css
    toc: true
    code-link: true
    include-in-header: assets/toggling.html
    sidebar: false
    number-sections: true
